### ISSUE TITLE
air or

### ISSUE THREAD

**Issue by NoSkillPureAndy** [VastraKai/McPatch#1]
[Patcher Error] An exception was thrown (please report this): System.ComponentModel.Win32Exception (299): Only part of a ReadProcessMemory or WriteProcessMemory request was completed.
   at System.Diagnostics.NtProcessManager.EnumProcessModulesUntilSuccess(SafeProcessHandle, IntPtr[], Int32, Int32& , Int32)
   at System.Diagnostics.NtProcessManager.GetModules(Int32, Boolean)
   at System.Diagnostics.NtProcessManager.GetFirstModule(Int32)
   at McPatch.Patcher.GetMcStuff()
   at McPatch.Patcher.Patch()
   at McPatch.Program.<>c__DisplayClass0_0.<Main>b__0()

**Comment by VastraKai** [comment]
skill issue tbh
